### ISSUE TITLE
Incorrect default date is selected

### ISSUE THREAD

**Issue by mp205** [Mulham-Raee/HorizontalCalendar#1]
Hi,
I have a small issue here, today it is 22nd January, but default date displayed on calendar is 26th January, even when I call "goToday" or "selectDate".

Also, the methods "getDateEndCalendar" and "getDateStartCalendar" return 22nd December and 22nd February, which is correct, but rendered dates are from 20th December to 24th February.

This is my code, I am not doing anything special.

```java
calendar = new HorizontalCalendar.Builder(layout, R.id.date_picker).build();
calendar.setCalendarListener(new CalendarListener(this));
```

and layout file

```xml
<devs.mulham.horizontalcalendar.HorizontalCalendarView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#fff"
                app:textColorNormal="#000"
                app:textColorSelected="#fff"
                app:selectorColor="#000"
                app:selectedDateBackground="#000"
                android:id="@+id/date_picker" />
```

EDIT: Building on Android 4.4.2 with appcompat-v7:25.1.0

**Comment by Mulham-Raee** [comment]
Hello @mp205 

If I understand correctly, `goToday()` method will select 26th January instead of 22nd January which is today, unfortunately I can't reproduce this bug although I used your code exactly, please try to post the steps u made to reproduce this bug.

Regarding End and Start Dates, there is no error here, this is the normal behavior of the calendar to render 2 days before and after the range, as the selected date should be always centered on the screen.
Please note that these extra 2 days are not selectable.

**Comment by mp205** [comment]
Hello, thank you for your answer, I will check it asap an I will report you if I see something

**Comment by mp205** [comment]
Hello again,
so I think, I figured it out. I have wrapped the calendar inside a LinearLayout, which had visibility set to gone, and I am displaying calendar after a button click.

Now, when I set LinearLayout's visibility to visible, everything is fine.

I just set it to visible, and I hide it instantly after the creation of calendar, in fragment's onCreateView method, so I get the expected result.

**Comment by Mulham-Raee** [comment]
Glad it worked out for you, actually `HorizontalCalendar` starts invisible then goes to visible after it finishes initialization so this might be the problem you faced.
I think setting the visibilty of your LinearLayout to **invisible** instead of **gone** will also work for you without hiding it in `OnCreateView`, since gone will not process any children at all.

**Comment by mp205** [comment]
I unfortunately cannot set **invisible** to layout, because it works as an overlay on other elements, so I would not be able to click other content behind it.
But now everything works great :)

**Comment by ArchanaKumari029** [comment]
correct date is getting selected but the thing is you have to use AppBarLayout and toolbar then it will work properly as library is showing.

**Comment by kadirgodil** [comment]
@Mulham-Raee On picking a date in horizontal calendar its picking a wrong date. For example I am selecting 28th December but its returning time for 27th December and the data stored for the timestamp of 28 will be shown on 29 selected next day its incrementing by oneday automatically  .Working fine on horizontal scrolling
Here's My code

 private void Calendar() {
        Calendar startDate = Calendar.getInstance();
        startDate.add(Calendar.DATE, -6);

        Calendar endDate = Calendar.getInstance();
        Date mEndDate = endDate.getTime();
        endDate.setTime(mEndDate);
        horizontalCalendar = new HorizontalCalendar.Builder(view, R.id.calendarView).range(startDate, endDate).datesNumberOnScreen(3).build();
     

        horizontalCalendar.setCalendarListener(new HorizontalCalendarListener() {
            @Override
            public void onDateSelected(Calendar date, int position) {
                //do something
                long dates = date.getTimeInMillis();
                Log.d("DATECHECK","Date : " + date.getTimeInMillis());
                Log.d("DATECHECK","Date : " + Myutils.Util.getToday());
                todayoffset = db.getSteps(dates);
                if (todayoffset >=0) {
                    totalsteps.setText(formatter.format(todayoffset));
                    float stepsize = prefs.getFloat("stepsize_value", ProfileFragment.DEFAULT_STEP_SIZE);
                    float distance_total = (todayoffset) * stepsize;
                    if (prefs.getString("stepsize_unit", ProfileFragment.DEFAULT_STEP_UNIT).equals("cm")) {
                        distance_total /= 100000;
                        unit = "km";

                    } else {
                        distance_total /= 5280;
                        unit = "mile";

                    }
                    totldistance.setText(formatter.format(distance_total));
                    totalCalories.setText(formatter.format(todayoffset * 0.04));
                } else {
                    totalsteps.setText("0");
                    totldistance.setText("0");
                    totalCalories.setText("0");
                }
            }
        });
        horizontalCalendar.refresh();
    }
