### ISSUE TITLE
Can't able to select last 2 elements.

### ISSUE THREAD

**Issue by shahwaiz90** [Mulham-Raee/HorizontalCalendar#4]
Restricts me to scroll more towards right or left to select the boundary elements.  So unable to select the boundary numbers.

**Comment by Mulham-Raee** [comment]
Hallo @shahwaiz90, 

There is no error here, this is the normal behavior of the calendar to render 2 days before and after the range, as the selected date should be always centered on the screen.
Theses extra days are **not selectable** obviously as they are not in the specified range!

If you want to select these dates you must adjust your **end** and **start** range using `HorizontalCalednar.Builder().startDate(Date start).endDate(Date end)`
